# Generated by Django 3.2.5 on 2021-08-05 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_doc', models.PositiveIntegerField()),
                ('country', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('job_type', models.CharField(choices=[('PA', 'Particular'), ('PU', 'Público'), ('PR', 'Privado')], max_length=20)),
                ('institution', models.CharField(max_length=150, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
