# Generated by Django 3.2.5 on 2021-11-12 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_plan',
            field=models.CharField(choices=[('FR', 'Free'), ('BA', 'Básico'), ('PR', 'Premium')], default='FR', max_length=20),
        ),
        migrations.CreateModel(
            name='ConsumedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analized_images', models.PositiveIntegerField(default=0)),
                ('_last_modified', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
